# Generated by Django 6.0.3 on 2026-03-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Domaine d’activité',
                'verbose_name_plural': 'Domaines d’activités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(db_index=True, max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('modalites_paiement', models.CharField(blank=True, max_length=255)),
                ('ninea_rc', models.CharField(blank=True, max_length=100)),
                ('demande_agrement', models.FileField(blank=True, null=True, upload_to='agrements/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], db_index=True, default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('domaines', models.ManyToManyField(blank=True, related_name='fournisseurs', to='fournisseurs.domaineactivite')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['raison_sociale'], name='fournisseur_raison__85b5b2_idx'), models.Index(fields=['statut'], name='fournisseur_statut_d32739_idx'), models.Index(fields=['email'], name='fournisseur_email_97f379_idx')],
            },
        ),
    ]
