# Generated by Django 6.0.3 on 2026-04-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_existing_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("fournisseurs", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user, defaults={"must_change_password": False}
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_domaineactivite_created_by_fournisseur_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='doit changer le mot de passe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateur',
            },
        ),
        migrations.RunPython(create_profiles_existing_users, noop_reverse),
    ]
