# Generated by Django 6.0.3 on 2026-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0006_criteres_evaluation_annuelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], db_index=True, default='en_attente', max_length=20),
        ),
    ]
